# Generated by Django 4.2.6 on 2024-02-10 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_role_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
