# Generated by Django 5.0.4 on 2024-04-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
